---
title: "Projects"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r metathis, message=FALSE, warning=FALSE, include=FALSE}
library(metathis)
library(htmltools)
source("R/functions.R")

```


```{r}
create_proj_card(
  img_src = "imgs/tidtuesday.png",
  url = "https://github.com/mcnakhaee/Tidy-Tuesday",
  title = "TidyTuesday",
  text = "My Submissions for the weekly TidyTuesday Project created using R and ggplot()",
  text2 =NULL)

create_proj_card(
  img_src = "imgs/delgosha.png",
  url = "https://github.com/mcnakhaee/delgosha",
  title = "{Delgosha}",
  text = "An R package which aims to provide a collection of
ggplot2 themes for RTL languages (mostly Persian)",
  text2 = NULL
)


create_proj_card(
  img_src = "imgs/palmer.png",
  url = "https://github.com/mcnakhaee/palmerpenguin",
  title = "{palmerpenguins}",
  text = "A python package for easily loading the Palmer penguins into your python environment",
  text2 = NULL
)
```

